-- MySQL Script generated by MySQL Workbench
-- Tue Mar 31 16:53:51 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema VenteChaussure
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `VenteChaussure` ;

-- -----------------------------------------------------
-- Schema VenteChaussure
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `VenteChaussure` DEFAULT CHARACTER SET utf8 ;
USE `VenteChaussure` ;

-- -----------------------------------------------------
-- Table `VenteChaussure`.`ville`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `VenteChaussure`.`ville` ;

CREATE TABLE IF NOT EXISTS `VenteChaussure`.`ville` (
  `idVille` INT NOT NULL AUTO_INCREMENT,
  `nomVille` VARCHAR(45) NOT NULL,
  `codeVille` INT(5) NOT NULL,
  PRIMARY KEY (`idVille`),
  UNIQUE INDEX `idVille_UNIQUE` (`idVille` ASC) )
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `VenteChaussure`.`client`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `VenteChaussure`.`client` ;

CREATE TABLE IF NOT EXISTS `VenteChaussure`.`client` (
  `idClient` INT NOT NULL AUTO_INCREMENT,
  `nomClient` VARCHAR(45) NOT NULL,
  `prenomClient` VARCHAR(45) NOT NULL,
  `emailClient` VARCHAR(320) NOT NULL,
  `mdpClient` VARCHAR(40) NOT NULL,
  `telClient` CHAR(10) NOT NULL,
  `residenceClient` VARCHAR(255) NOT NULL,
  `ville_idVille` INT NOT NULL,
  PRIMARY KEY (`idClient`, `ville_idVille`),
  UNIQUE INDEX `idClient_UNIQUE` (`idClient` ASC) ,
  INDEX `fk_client_ville1_idx` (`ville_idVille` ASC) ,
  CONSTRAINT `fk_client_ville1`
    FOREIGN KEY (`ville_idVille`)
    REFERENCES `VenteChaussure`.`ville` (`idVille`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `VenteChaussure`.`panier`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `VenteChaussure`.`panier` ;

CREATE TABLE IF NOT EXISTS `VenteChaussure`.`panier` (
  `idpanier` INT NOT NULL AUTO_INCREMENT,
  `validerPanier` INT(2) NULL DEFAULT 0,
  PRIMARY KEY (`idpanier`),
  UNIQUE INDEX `idpanier_UNIQUE` (`idpanier` ASC) )
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `VenteChaussure`.`commentaires`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `VenteChaussure`.`commentaires` ;

CREATE TABLE IF NOT EXISTS `VenteChaussure`.`commentaires` (
  `idCommentaires` INT NOT NULL AUTO_INCREMENT,
  `textCommentaire` VARCHAR(255) NOT NULL,
  `dateCommentaire` DATETIME NOT NULL,
  `client_idClient` INT NOT NULL,
  PRIMARY KEY (`idCommentaires`, `client_idClient`),
  UNIQUE INDEX `idCommentaires_UNIQUE` (`idCommentaires` ASC) ,
  INDEX `fk_commentaires_client1_idx` (`client_idClient` ASC) ,
  CONSTRAINT `fk_commentaires_client1`
    FOREIGN KEY (`client_idClient`)
    REFERENCES `VenteChaussure`.`client` (`idClient`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `VenteChaussure`.`variante`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `VenteChaussure`.`variante` ;

CREATE TABLE IF NOT EXISTS `VenteChaussure`.`variante` (
  `idVariante` INT NOT NULL,
  `couleurVariante` VARCHAR(45) NOT NULL,
  `tailleVariante` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idVariante`),
  UNIQUE INDEX `idVariante_UNIQUE` (`idVariante` ASC) )
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `VenteChaussure`.`produit`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `VenteChaussure`.`produit` ;

CREATE TABLE IF NOT EXISTS `VenteChaussure`.`produit` (
  `idproduit` INT NOT NULL AUTO_INCREMENT,
  `prixProduit` INT(6) NOT NULL,
  `quantiteProduit` INT NOT NULL,
  `commentaires_idCommentaires` INT NOT NULL,
  `variante_idVariante` INT NOT NULL,
  PRIMARY KEY (`idproduit`, `commentaires_idCommentaires`, `variante_idVariante`),
  UNIQUE INDEX `idproduit_UNIQUE` (`idproduit` ASC) ,
  INDEX `fk_produit_commentaires1_idx` (`commentaires_idCommentaires` ASC) ,
  INDEX `fk_produit_variante1_idx` (`variante_idVariante` ASC) ,
  CONSTRAINT `fk_produit_commentaires1`
    FOREIGN KEY (`commentaires_idCommentaires`)
    REFERENCES `VenteChaussure`.`commentaires` (`idCommentaires`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_produit_variante1`
    FOREIGN KEY (`variante_idVariante`)
    REFERENCES `VenteChaussure`.`variante` (`idVariante`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `VenteChaussure`.`detenir`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `VenteChaussure`.`detenir` ;

CREATE TABLE IF NOT EXISTS `VenteChaussure`.`detenir` (
  `client_idClient` INT NOT NULL,
  `panier_idpanier` INT NOT NULL,
  PRIMARY KEY (`client_idClient`, `panier_idpanier`),
  INDEX `fk_detenir_panier1_idx` (`panier_idpanier` ASC) ,
  CONSTRAINT `fk_detenir_client`
    FOREIGN KEY (`client_idClient`)
    REFERENCES `VenteChaussure`.`client` (`idClient`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_detenir_panier1`
    FOREIGN KEY (`panier_idpanier`)
    REFERENCES `VenteChaussure`.`panier` (`idpanier`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `VenteChaussure`.`contenir`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `VenteChaussure`.`contenir` ;

CREATE TABLE IF NOT EXISTS `VenteChaussure`.`contenir` (
  `produit_idproduit` INT NOT NULL,
  `panier_idpanier` INT NOT NULL,
  PRIMARY KEY (`produit_idproduit`, `panier_idpanier`),
  INDEX `fk_contenir_panier1_idx` (`panier_idpanier` ASC) ,
  CONSTRAINT `fk_contenir_produit1`
    FOREIGN KEY (`produit_idproduit`)
    REFERENCES `VenteChaussure`.`produit` (`idproduit`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_contenir_panier1`
    FOREIGN KEY (`panier_idpanier`)
    REFERENCES `VenteChaussure`.`panier` (`idpanier`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `VenteChaussure`.`facture`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `VenteChaussure`.`facture` ;

CREATE TABLE IF NOT EXISTS `VenteChaussure`.`facture` (
  `idFacture` INT NOT NULL AUTO_INCREMENT,
  `dateFacture` DATE NOT NULL,
  `panier_idpanier` INT NOT NULL,
  PRIMARY KEY (`idFacture`, `panier_idpanier`),
  UNIQUE INDEX `idFacture_UNIQUE` (`idFacture` ASC) ,
  INDEX `fk_facture_panier1_idx` (`panier_idpanier` ASC) ,
  CONSTRAINT `fk_facture_panier1`
    FOREIGN KEY (`panier_idpanier`)
    REFERENCES `VenteChaussure`.`panier` (`idpanier`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `VenteChaussure`.`fournisseurs`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `VenteChaussure`.`fournisseurs` ;

CREATE TABLE IF NOT EXISTS `VenteChaussure`.`fournisseurs` (
  `idFournisseur` INT NOT NULL AUTO_INCREMENT,
  `nomFourniseur` VARCHAR(45) NOT NULL,
  `residenceFournisseur` VARCHAR(255) NOT NULL,
  `produit_idproduit` INT NOT NULL,
  `produit_variante_idVariante` INT NOT NULL,
  `ville_idVille` INT NOT NULL,
  PRIMARY KEY (`idFournisseur`, `produit_idproduit`, `produit_variante_idVariante`, `ville_idVille`),
  UNIQUE INDEX `idFournisseur_UNIQUE` (`idFournisseur` ASC) ,
  INDEX `fk_fournisseurs_produit1_idx` (`produit_idproduit` ASC, `produit_variante_idVariante` ASC) ,
  INDEX `fk_fournisseurs_ville1_idx` (`ville_idVille` ASC) ,
  CONSTRAINT `fk_fournisseurs_produit1`
    FOREIGN KEY (`produit_idproduit` , `produit_variante_idVariante`)
    REFERENCES `VenteChaussure`.`produit` (`idproduit` , `variante_idVariante`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_fournisseurs_ville1`
    FOREIGN KEY (`ville_idVille`)
    REFERENCES `VenteChaussure`.`ville` (`idVille`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `VenteChaussure`.`utilisateur`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `VenteChaussure`.`utilisateur` ;

CREATE TABLE IF NOT EXISTS `VenteChaussure`.`utilisateur` (
  `idUtilisateur` INT NOT NULL AUTO_INCREMENT,
  `loginUtilisateur` VARCHAR(320) NOT NULL,
  `mdpUtilisateur` VARCHAR(40) NOT NULL,
  PRIMARY KEY (`idUtilisateur`),
  UNIQUE INDEX `idUtilisateur_UNIQUE` (`idUtilisateur` ASC) )
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `VenteChaussure`.`privilege`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `VenteChaussure`.`privilege` ;

CREATE TABLE IF NOT EXISTS `VenteChaussure`.`privilege` (
  `idPrivilege` INT NOT NULL AUTO_INCREMENT,
  `typePrivilege` VARCHAR(45) NOT NULL,
  `descriptionPrivilege` VARCHAR(255) NOT NULL,
  `utilisateur_idUtilisateur` INT NOT NULL,
  PRIMARY KEY (`idPrivilege`, `utilisateur_idUtilisateur`),
  UNIQUE INDEX `idPrivilege_UNIQUE` (`idPrivilege` ASC) ,
  INDEX `fk_privilege_utilisateur1_idx` (`utilisateur_idUtilisateur` ASC) ,
  CONSTRAINT `fk_privilege_utilisateur1`
    FOREIGN KEY (`utilisateur_idUtilisateur`)
    REFERENCES `VenteChaussure`.`utilisateur` (`idUtilisateur`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
