-- MySQL Script generated by MySQL Workbench
-- Tue Mar 31 14:20:53 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema VenteChaussure
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `VenteChaussure` ;

-- -----------------------------------------------------
-- Schema VenteChaussure
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `VenteChaussure` DEFAULT CHARACTER SET utf8 ;
USE `VenteChaussure` ;

-- -----------------------------------------------------
-- Table `VenteChaussure`.`client`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `VenteChaussure`.`client` ;

CREATE TABLE IF NOT EXISTS `VenteChaussure`.`client` (
  `idClient` INT NOT NULL AUTO_INCREMENT,
  `nomClient` VARCHAR(45) NOT NULL,
  `prenomClient` VARCHAR(45) NOT NULL,
  `emailClient` VARCHAR(320) NOT NULL,
  `mdpClient` VARCHAR(40) NOT NULL,
  `telClient` CHAR(10) NOT NULL,
  `residenceClient` VARCHAR(255) NOT NULL,
  `idVille` INT NOT NULL,
  PRIMARY KEY (`idClient`),
  UNIQUE INDEX `idClient_UNIQUE` (`idClient` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `VenteChaussure`.`panier`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `VenteChaussure`.`panier` ;

CREATE TABLE IF NOT EXISTS `VenteChaussure`.`panier` (
  `idpanier` INT NOT NULL AUTO_INCREMENT,
  `validerPanier` INT(2) NULL DEFAULT 0,
  PRIMARY KEY (`idpanier`),
  UNIQUE INDEX `idpanier_UNIQUE` (`idpanier` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `VenteChaussure`.`commentaires`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `VenteChaussure`.`commentaires` ;

CREATE TABLE IF NOT EXISTS `VenteChaussure`.`commentaires` (
  `idCommentaires` INT NOT NULL AUTO_INCREMENT,
  `textCommentaire` VARCHAR(255) NOT NULL,
  `dateCommentaire` DATETIME NOT NULL,
  `client_idClient` INT NOT NULL,
  PRIMARY KEY (`idCommentaires`, `client_idClient`),
  UNIQUE INDEX `idCommentaires_UNIQUE` (`idCommentaires` ASC) VISIBLE,
  INDEX `fk_commentaires_client1_idx` (`client_idClient` ASC) VISIBLE,
  CONSTRAINT `fk_commentaires_client1`
    FOREIGN KEY (`client_idClient`)
    REFERENCES `VenteChaussure`.`client` (`idClient`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `VenteChaussure`.`produit`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `VenteChaussure`.`produit` ;

CREATE TABLE IF NOT EXISTS `VenteChaussure`.`produit` (
  `idproduit` INT NOT NULL AUTO_INCREMENT,
  `prixProduit` INT(6) NOT NULL,
  `quantiteProduit` INT NOT NULL,
  `commentaires_idCommentaires` INT NOT NULL,
  `commentaires_client_idClient` INT NOT NULL,
  PRIMARY KEY (`idproduit`, `commentaires_idCommentaires`, `commentaires_client_idClient`),
  UNIQUE INDEX `idproduit_UNIQUE` (`idproduit` ASC) VISIBLE,
  INDEX `fk_produit_commentaires1_idx` (`commentaires_idCommentaires` ASC, `commentaires_client_idClient` ASC) VISIBLE,
  CONSTRAINT `fk_produit_commentaires1`
    FOREIGN KEY (`commentaires_idCommentaires` , `commentaires_client_idClient`)
    REFERENCES `VenteChaussure`.`commentaires` (`idCommentaires` , `client_idClient`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `VenteChaussure`.`detenir`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `VenteChaussure`.`detenir` ;

CREATE TABLE IF NOT EXISTS `VenteChaussure`.`detenir` (
  `client_idClient` INT NOT NULL,
  `panier_idpanier` INT NOT NULL,
  PRIMARY KEY (`client_idClient`, `panier_idpanier`),
  INDEX `fk_detenir_panier1_idx` (`panier_idpanier` ASC) VISIBLE,
  CONSTRAINT `fk_detenir_client`
    FOREIGN KEY (`client_idClient`)
    REFERENCES `VenteChaussure`.`client` (`idClient`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_detenir_panier1`
    FOREIGN KEY (`panier_idpanier`)
    REFERENCES `VenteChaussure`.`panier` (`idpanier`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `VenteChaussure`.`contenir`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `VenteChaussure`.`contenir` ;

CREATE TABLE IF NOT EXISTS `VenteChaussure`.`contenir` (
  `produit_idproduit` INT NOT NULL,
  `panier_idpanier` INT NOT NULL,
  PRIMARY KEY (`produit_idproduit`, `panier_idpanier`),
  INDEX `fk_contenir_panier1_idx` (`panier_idpanier` ASC) VISIBLE,
  CONSTRAINT `fk_contenir_produit1`
    FOREIGN KEY (`produit_idproduit`)
    REFERENCES `VenteChaussure`.`produit` (`idproduit`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_contenir_panier1`
    FOREIGN KEY (`panier_idpanier`)
    REFERENCES `VenteChaussure`.`panier` (`idpanier`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `VenteChaussure`.`facture`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `VenteChaussure`.`facture` ;

CREATE TABLE IF NOT EXISTS `VenteChaussure`.`facture` (
  `idFacture` INT NOT NULL AUTO_INCREMENT,
  `dateFacture` DATE NOT NULL,
  `panier_idpanier` INT NOT NULL,
  PRIMARY KEY (`idFacture`, `panier_idpanier`),
  UNIQUE INDEX `idFacture_UNIQUE` (`idFacture` ASC) VISIBLE,
  INDEX `fk_facture_panier1_idx` (`panier_idpanier` ASC) VISIBLE,
  CONSTRAINT `fk_facture_panier1`
    FOREIGN KEY (`panier_idpanier`)
    REFERENCES `VenteChaussure`.`panier` (`idpanier`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
