-- MySQL Script generated by MySQL Workbench
-- Tue Mar 31 13:06:29 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema VenteChaussure
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `VenteChaussure` ;

-- -----------------------------------------------------
-- Schema VenteChaussure
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `VenteChaussure` DEFAULT CHARACTER SET utf8 ;
USE `VenteChaussure` ;

-- -----------------------------------------------------
-- Table `VenteChaussure`.`client`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `VenteChaussure`.`client` ;

CREATE TABLE IF NOT EXISTS `VenteChaussure`.`client` (
  `idClient` INT NOT NULL AUTO_INCREMENT,
  `nomClient` VARCHAR(45) NOT NULL,
  `prenomClient` VARCHAR(45) NOT NULL,
  `emailClient` VARCHAR(320) NOT NULL,
  `mdpClient` VARCHAR(40) NOT NULL,
  `telClient` CHAR(10) NOT NULL,
  `residenceClient` VARCHAR(255) NOT NULL,
  `idVille` INT NOT NULL,
  PRIMARY KEY (`idClient`),
  UNIQUE INDEX `idClient_UNIQUE` (`idClient` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `VenteChaussure`.`panier`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `VenteChaussure`.`panier` ;

CREATE TABLE IF NOT EXISTS `VenteChaussure`.`panier` (
  `idpanier` INT NOT NULL AUTO_INCREMENT,
  `validerPanier` INT(2) NULL DEFAULT 0,
  `id_produit` INT NOT NULL,
  `id_client` INT NOT NULL,
  PRIMARY KEY (`idpanier`),
  UNIQUE INDEX `idpanier_UNIQUE` (`idpanier` ASC) VISIBLE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
