-- MySQL Script generated by MySQL Workbench
-- Thu Apr  9 18:38:15 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema projetImmo
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `projetImmo` ;

-- -----------------------------------------------------
-- Schema projetImmo
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `projetImmo` DEFAULT CHARACTER SET utf8 ;
USE `projetImmo` ;

-- -----------------------------------------------------
-- Table `projetImmo`.`ville`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `projetImmo`.`ville` ;

CREATE TABLE IF NOT EXISTS `projetImmo`.`ville` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nomville` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `projetImmo`.`pays`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `projetImmo`.`pays` ;

CREATE TABLE IF NOT EXISTS `projetImmo`.`pays` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nomPays` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `projetImmo`.`contact`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `projetImmo`.`contact` ;

CREATE TABLE IF NOT EXISTS `projetImmo`.`contact` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `email` VARCHAR(45) NOT NULL,
  `adresse` VARCHAR(100) NOT NULL,
  `adresse2` VARCHAR(45) NULL,
  `zip` VARCHAR(45) NOT NULL,
  `ville_id` INT NOT NULL,
  `pays_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  INDEX `fk_contact_ville_idx` (`ville_id` ASC),
  INDEX `fk_contact_pays1_idx` (`pays_id` ASC),
  CONSTRAINT `fk_contact_ville`
    FOREIGN KEY (`ville_id`)
    REFERENCES `projetImmo`.`ville` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_contact_pays1`
    FOREIGN KEY (`pays_id`)
    REFERENCES `projetImmo`.`pays` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `projetImmo`.`detail`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `projetImmo`.`detail` ;

CREATE TABLE IF NOT EXISTS `projetImmo`.`detail` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `photo` VARCHAR(45) NOT NULL,
  `description` TEXT NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `projetImmo`.`location`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `projetImmo`.`location` ;

CREATE TABLE IF NOT EXISTS `projetImmo`.`location` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nom` VARCHAR(50) NOT NULL,
  `prix` INT NOT NULL,
  `detail_id` INT UNSIGNED NOT NULL,
  `contact_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  INDEX `fk_location_detail1_idx` (`detail_id` ASC),
  INDEX `fk_location_contact1_idx` (`contact_id` ASC),
  CONSTRAINT `fk_location_detail1`
    FOREIGN KEY (`detail_id`)
    REFERENCES `projetImmo`.`detail` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_location_contact1`
    FOREIGN KEY (`contact_id`)
    REFERENCES `projetImmo`.`contact` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
