-- MySQL Script generated by MySQL Workbench
-- Fri Apr 10 12:46:38 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema projetimmo
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `projetimmo` ;

-- -----------------------------------------------------
-- Schema projetimmo
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `projetimmo` DEFAULT CHARACTER SET utf8 ;
USE `projetimmo` ;

-- -----------------------------------------------------
-- Table `projetimmo`.`adresse`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `projetimmo`.`adresse` ;

CREATE TABLE IF NOT EXISTS `projetimmo`.`adresse` (
  `idadresse` INT NOT NULL AUTO_INCREMENT,
  `adresse1` VARCHAR(100) NOT NULL,
  `adresse2` VARCHAR(100) NULL,
  `codepostal` INT(5) NOT NULL,
  `pays` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`idadresse`),
  UNIQUE INDEX `idadresse_UNIQUE` (`idadresse` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `projetimmo`.`contact`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `projetimmo`.`contact` ;

CREATE TABLE IF NOT EXISTS `projetimmo`.`contact` (
  `idcontact` INT NOT NULL AUTO_INCREMENT,
  `Email` VARCHAR(100) NOT NULL,
  `messageContact` TEXT(10000) NULL,
  `adresse_idadresse` INT NOT NULL,
  UNIQUE INDEX `idcontact_UNIQUE` (`idcontact` ASC),
  PRIMARY KEY (`idcontact`),
  INDEX `fk_contact_adresse1_idx` (`adresse_idadresse` ASC),
  CONSTRAINT `fk_contact_adresse1`
    FOREIGN KEY (`adresse_idadresse`)
    REFERENCES `projetimmo`.`adresse` (`idadresse`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `projetimmo`.`detail`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `projetimmo`.`detail` ;

CREATE TABLE IF NOT EXISTS `projetimmo`.`detail` (
  `iddetail` INT NOT NULL AUTO_INCREMENT,
  `Superficiecdetail` INT(11) NOT NULL,
  `nbPiecedetail` INT(2) NOT NULL,
  `descdetail` TEXT(10000) NOT NULL,
  PRIMARY KEY (`iddetail`),
  UNIQUE INDEX `iddetail_UNIQUE` (`iddetail` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `projetimmo`.`location`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `projetimmo`.`location` ;

CREATE TABLE IF NOT EXISTS `projetimmo`.`location` (
  `idlocation` INT NOT NULL AUTO_INCREMENT,
  `titreLocation` VARCHAR(100) NOT NULL,
  `resumeLocation` VARCHAR(100) NOT NULL,
  `imageLocation` VARCHAR(255) NOT NULL,
  `statusLocation` TINYINT(1) NULL,
  `dateCreaLocation` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `dateModifLocation` DATETIME NULL,
  `detail_iddetail` INT NOT NULL,
  PRIMARY KEY (`idlocation`),
  INDEX `fk_location_detail_idx` (`detail_iddetail` ASC),
  CONSTRAINT `fk_location_detail`
    FOREIGN KEY (`detail_iddetail`)
    REFERENCES `projetimmo`.`detail` (`iddetail`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `projetimmo`.`agence`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `projetimmo`.`agence` ;

CREATE TABLE IF NOT EXISTS `projetimmo`.`agence` (
  `idagence` INT NOT NULL AUTO_INCREMENT,
  `nomAgence` VARCHAR(100) NOT NULL,
  `nomRepreAgence` VARCHAR(100) NOT NULL,
  `prenomRepreAgence` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`idagence`),
  UNIQUE INDEX `idagence_UNIQUE` (`idagence` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `projetimmo`.`agence_has_location`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `projetimmo`.`agence_has_location` ;

CREATE TABLE IF NOT EXISTS `projetimmo`.`agence_has_location` (
  `agence_idagence` INT NOT NULL,
  `location_idlocation` INT NOT NULL,
  PRIMARY KEY (`agence_idagence`, `location_idlocation`),
  INDEX `fk_agence_has_location_location1_idx` (`location_idlocation` ASC),
  INDEX `fk_agence_has_location_agence1_idx` (`agence_idagence` ASC),
  CONSTRAINT `fk_agence_has_location_agence1`
    FOREIGN KEY (`agence_idagence`)
    REFERENCES `projetimmo`.`agence` (`idagence`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_agence_has_location_location1`
    FOREIGN KEY (`location_idlocation`)
    REFERENCES `projetimmo`.`location` (`idlocation`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `projetimmo`.`client`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `projetimmo`.`client` ;

CREATE TABLE IF NOT EXISTS `projetimmo`.`client` (
  `idclient` INT NOT NULL AUTO_INCREMENT,
  `nomClient` VARCHAR(100) NOT NULL,
  `prenomClient` VARCHAR(100) NOT NULL,
  `mdpClient` VARCHAR(100) NOT NULL,
  `agence_idagence` INT NOT NULL,
  `adresse_idadresse` INT NOT NULL,
  PRIMARY KEY (`idclient`),
  UNIQUE INDEX `idclient_UNIQUE` (`idclient` ASC),
  INDEX `fk_client_agence1_idx` (`agence_idagence` ASC),
  INDEX `fk_client_adresse1_idx` (`adresse_idadresse` ASC),
  CONSTRAINT `fk_client_agence1`
    FOREIGN KEY (`agence_idagence`)
    REFERENCES `projetimmo`.`agence` (`idagence`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_client_adresse1`
    FOREIGN KEY (`adresse_idadresse`)
    REFERENCES `projetimmo`.`adresse` (`idadresse`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;