-- MySQL Script generated by MySQL Workbench
-- Wed Apr  1 10:52:37 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema default_schema
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema VenteChaussure
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `VenteChaussure` ;

-- -----------------------------------------------------
-- Schema VenteChaussure
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `VenteChaussure` DEFAULT CHARACTER SET utf8 ;
USE `VenteChaussure` ;

-- -----------------------------------------------------
-- Table `VenteChaussure`.`ville`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `VenteChaussure`.`ville` ;

CREATE TABLE IF NOT EXISTS `VenteChaussure`.`ville` (
  `idVille` INT NOT NULL AUTO_INCREMENT,
  `nomVille` VARCHAR(45) NOT NULL,
  `codeVille` INT(5) NOT NULL,
  PRIMARY KEY (`idVille`),
  UNIQUE INDEX `idVille_UNIQUE` (`idVille` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `VenteChaussure`.`TypeUser`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `VenteChaussure`.`TypeUser` ;

CREATE TABLE IF NOT EXISTS `VenteChaussure`.`TypeUser` (
  `idTypeUser` INT NOT NULL AUTO_INCREMENT,
  `nomTypeUser` VARCHAR(45) NULL,
  PRIMARY KEY (`idTypeUser`),
  UNIQUE INDEX `idTypeUser_UNIQUE` (`idTypeUser` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `VenteChaussure`.`User`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `VenteChaussure`.`User` ;

CREATE TABLE IF NOT EXISTS `VenteChaussure`.`User` (
  `idUser` INT NOT NULL AUTO_INCREMENT,
  `nomUser` VARCHAR(45) NOT NULL,
  `prenomUser` VARCHAR(45) NOT NULL,
  `emailUser` VARCHAR(320) NOT NULL,
  `mdpUser` VARCHAR(40) NOT NULL,
  `telUser` CHAR(10) NOT NULL,
  `residenceUser` VARCHAR(255) NOT NULL,
  `roleUser` VARCHAR(45) NULL,
  `TypeUser_idTypeUser` INT NOT NULL,
  `ville_idVille` INT NOT NULL,
  PRIMARY KEY (`idUser`),
  UNIQUE INDEX `idClient_UNIQUE` (`idUser` ASC),
  INDEX `fk_User_TypeUser1_idx` (`TypeUser_idTypeUser` ASC),
  INDEX `fk_User_ville1_idx` (`ville_idVille` ASC),
  CONSTRAINT `fk_User_TypeUser1`
    FOREIGN KEY (`TypeUser_idTypeUser`)
    REFERENCES `VenteChaussure`.`TypeUser` (`idTypeUser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_User_ville1`
    FOREIGN KEY (`ville_idVille`)
    REFERENCES `VenteChaussure`.`ville` (`idVille`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `VenteChaussure`.`Color`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `VenteChaussure`.`Color` ;

CREATE TABLE IF NOT EXISTS `VenteChaussure`.`Color` (
  `idColor` INT NOT NULL,
  `nomColor` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idColor`),
  UNIQUE INDEX `idVariante_UNIQUE` (`idColor` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `VenteChaussure`.`Taille`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `VenteChaussure`.`Taille` ;

CREATE TABLE IF NOT EXISTS `VenteChaussure`.`Taille` (
  `idTaille` INT NOT NULL,
  `nomTaille` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idTaille`),
  UNIQUE INDEX `idVariante_UNIQUE` (`idTaille` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `VenteChaussure`.`produit`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `VenteChaussure`.`produit` ;

CREATE TABLE IF NOT EXISTS `VenteChaussure`.`produit` (
  `idproduit` INT NOT NULL AUTO_INCREMENT,
  `prixProduit` INT(6) NOT NULL,
  `quantiteProduit` INT NOT NULL,
  `commentaire` LONGTEXT NULL,
  `dateCommentaires` DATETIME NULL,
  `Taille_idTaille` INT NOT NULL,
  `Color_idColor` INT NOT NULL,
  PRIMARY KEY (`idproduit`),
  UNIQUE INDEX `idproduit_UNIQUE` (`idproduit` ASC),
  INDEX `fk_produit_Taille1_idx` (`Taille_idTaille` ASC),
  INDEX `fk_produit_Color1_idx` (`Color_idColor` ASC),
  CONSTRAINT `fk_produit_Taille1`
    FOREIGN KEY (`Taille_idTaille`)
    REFERENCES `VenteChaussure`.`Taille` (`idTaille`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_produit_Color1`
    FOREIGN KEY (`Color_idColor`)
    REFERENCES `VenteChaussure`.`Color` (`idColor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `VenteChaussure`.`facture`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `VenteChaussure`.`facture` ;

CREATE TABLE IF NOT EXISTS `VenteChaussure`.`facture` (
  `idFacture` INT NOT NULL AUTO_INCREMENT,
  `dateFacture` DATE NOT NULL,
  `numfacture` INT NOT NULL,
  PRIMARY KEY (`idFacture`),
  UNIQUE INDEX `idFacture_UNIQUE` (`idFacture` ASC),
  UNIQUE INDEX `numfacture_UNIQUE` (`numfacture` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `VenteChaussure`.`Commande`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `VenteChaussure`.`Commande` ;

CREATE TABLE IF NOT EXISTS `VenteChaussure`.`Commande` (
  `User_idUser` INT NOT NULL,
  `panier_idpanier` INT NOT NULL,
  `dateCommande` DATETIME NULL,
  `quantiteCde` INT NULL,
  `statut` TINYINT NULL,
  `produit_idproduit` INT NOT NULL,
  `facture_idFacture` INT NOT NULL,
  PRIMARY KEY (`User_idUser`, `panier_idpanier`),
  INDEX `fk_User_has_panier_User1_idx` (`User_idUser` ASC),
  INDEX `fk_Commande_produit1_idx` (`produit_idproduit` ASC),
  INDEX `fk_Commande_facture1_idx` (`facture_idFacture` ASC),
  CONSTRAINT `fk_User_has_panier_User1`
    FOREIGN KEY (`User_idUser`)
    REFERENCES `VenteChaussure`.`User` (`idUser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Commande_produit1`
    FOREIGN KEY (`produit_idproduit`)
    REFERENCES `VenteChaussure`.`produit` (`idproduit`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Commande_facture1`
    FOREIGN KEY (`facture_idFacture`)
    REFERENCES `VenteChaussure`.`facture` (`idFacture`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
