-- MySQL Script generated by MySQL Workbench
-- Wed Apr  1 18:19:14 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema Chaussure
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `Chaussure` ;

-- -----------------------------------------------------
-- Schema Chaussure
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Chaussure` DEFAULT CHARACTER SET utf8 ;
USE `Chaussure` ;

-- -----------------------------------------------------
-- Table `Chaussure`.`TypeUser`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Chaussure`.`TypeUser` ;

CREATE TABLE IF NOT EXISTS `Chaussure`.`TypeUser` (
  `idTypeUser` INT NOT NULL AUTO_INCREMENT,
  `nomTypeUser` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idTypeUser`),
  UNIQUE INDEX `idTypeUser_UNIQUE` (`idTypeUser` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Chaussure`.`RegionDept`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Chaussure`.`RegionDept` ;

CREATE TABLE IF NOT EXISTS `Chaussure`.`RegionDept` (
  `idRegionDept` INT NOT NULL AUTO_INCREMENT,
  `numDept` INT NOT NULL,
  `nomDept` VARCHAR(45) NOT NULL,
  `nomRegion` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idRegionDept`),
  UNIQUE INDEX `idRegionDept_UNIQUE` (`idRegionDept` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Chaussure`.`Ville`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Chaussure`.`Ville` ;

CREATE TABLE IF NOT EXISTS `Chaussure`.`Ville` (
  `idVille` INT NOT NULL AUTO_INCREMENT,
  `cpVille` VARCHAR(45) NOT NULL,
  `nomVille` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idVille`),
  UNIQUE INDEX `idVille_UNIQUE` (`idVille` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Chaussure`.`TVA`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Chaussure`.`TVA` ;

CREATE TABLE IF NOT EXISTS `Chaussure`.`TVA` (
  `idTVA` INT NOT NULL AUTO_INCREMENT,
  `nomTVA` VARCHAR(45) NOT NULL,
  `statutTVA` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idTVA`),
  UNIQUE INDEX `idTVA_UNIQUE` (`idTVA` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Chaussure`.`User`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Chaussure`.`User` ;

CREATE TABLE IF NOT EXISTS `Chaussure`.`User` (
  `idUser` INT NOT NULL AUTO_INCREMENT,
  `nomUser` VARCHAR(255) NOT NULL,
  `prenomUser` VARCHAR(45) NULL,
  `numRueUser` INT NOT NULL,
  `nomRueUser` VARCHAR(255) NULL,
  `mailUser` VARCHAR(255) NOT NULL,
  `phoneUser` VARCHAR(10) NULL,
  `paysUser` VARCHAR(45) NOT NULL,
  `statutUser` TINYINT NULL,
  `TypeUser_idTypeUser` INT NOT NULL,
  `RegionDept_idRegionDept` INT NOT NULL,
  `Ville_idVille` INT NOT NULL,
  `TVA_idTVA` INT NOT NULL,
  PRIMARY KEY (`idUser`),
  UNIQUE INDEX `idUser_UNIQUE` (`idUser` ASC),
  INDEX `fk_User_TypeUser1_idx` (`TypeUser_idTypeUser` ASC),
  INDEX `fk_User_RegionDept1_idx` (`RegionDept_idRegionDept` ASC),
  INDEX `fk_User_Ville1_idx` (`Ville_idVille` ASC),
  INDEX `fk_User_TVA1_idx` (`TVA_idTVA` ASC),
  CONSTRAINT `fk_User_TypeUser1`
    FOREIGN KEY (`TypeUser_idTypeUser`)
    REFERENCES `Chaussure`.`TypeUser` (`idTypeUser`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_User_RegionDept1`
    FOREIGN KEY (`RegionDept_idRegionDept`)
    REFERENCES `Chaussure`.`RegionDept` (`idRegionDept`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_User_Ville1`
    FOREIGN KEY (`Ville_idVille`)
    REFERENCES `Chaussure`.`Ville` (`idVille`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_User_TVA1`
    FOREIGN KEY (`TVA_idTVA`)
    REFERENCES `Chaussure`.`TVA` (`idTVA`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Chaussure`.`Banque`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Chaussure`.`Banque` ;

CREATE TABLE IF NOT EXISTS `Chaussure`.`Banque` (
  `idBanque` INT NOT NULL AUTO_INCREMENT,
  `nomBanque` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`idBanque`),
  UNIQUE INDEX `idBanque_UNIQUE` (`idBanque` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Chaussure`.`Commande`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Chaussure`.`Commande` ;

CREATE TABLE IF NOT EXISTS `Chaussure`.`Commande` (
  `idCommande` INT NOT NULL AUTO_INCREMENT,
  `qte` INT NOT NULL,
  `datCommande` DATETIME NULL,
  `User_idUser` INT NOT NULL,
  PRIMARY KEY (`idCommande`),
  UNIQUE INDEX `idCommande_UNIQUE` (`idCommande` ASC),
  INDEX `fk_Commande_User1_idx` (`User_idUser` ASC),
  CONSTRAINT `fk_Commande_User1`
    FOREIGN KEY (`User_idUser`)
    REFERENCES `Chaussure`.`User` (`idUser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Chaussure`.`Entreprot`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Chaussure`.`Entreprot` ;

CREATE TABLE IF NOT EXISTS `Chaussure`.`Entreprot` (
  `idEntreprot` INT NOT NULL AUTO_INCREMENT,
  `nomEntreprot` VARCHAR(45) NOT NULL,
  `qte` INT NOT NULL,
  `statutEntrepot` TINYINT NULL,
  PRIMARY KEY (`idEntreprot`),
  UNIQUE INDEX `idEntreprot_UNIQUE` (`idEntreprot` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Chaussure`.`Taille`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Chaussure`.`Taille` ;

CREATE TABLE IF NOT EXISTS `Chaussure`.`Taille` (
  `idTaille` INT NOT NULL AUTO_INCREMENT,
  `nomTaille` INT NOT NULL,
  `statutTaille` TINYINT NOT NULL,
  PRIMARY KEY (`idTaille`),
  UNIQUE INDEX `idTaille_UNIQUE` (`idTaille` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Chaussure`.`Couleur`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Chaussure`.`Couleur` ;

CREATE TABLE IF NOT EXISTS `Chaussure`.`Couleur` (
  `idCouleur` INT NOT NULL AUTO_INCREMENT,
  `nomCouleur` VARCHAR(45) NOT NULL,
  `statutCouleur` TINYINT NOT NULL,
  PRIMARY KEY (`idCouleur`),
  UNIQUE INDEX `idCouleur_UNIQUE` (`idCouleur` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Chaussure`.`Materiel`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Chaussure`.`Materiel` ;

CREATE TABLE IF NOT EXISTS `Chaussure`.`Materiel` (
  `idMateriel` INT NOT NULL AUTO_INCREMENT,
  `nomMateriel` VARCHAR(45) NOT NULL,
  `statutMateriel` TINYINT NOT NULL,
  PRIMARY KEY (`idMateriel`),
  UNIQUE INDEX `idMateriel_UNIQUE` (`idMateriel` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Chaussure`.`Produit`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Chaussure`.`Produit` ;

CREATE TABLE IF NOT EXISTS `Chaussure`.`Produit` (
  `idProduit` INT NOT NULL AUTO_INCREMENT,
  `nomProduit` VARCHAR(45) NOT NULL,
  `descProduit` VARCHAR(45) NULL,
  `prixHTProduit` DECIMAL(6) NOT NULL,
  `refProduit` VARCHAR(255) NOT NULL,
  `vipProduit` VARCHAR(45) NULL,
  `noteProduit` INT NULL,
  `statutproduit` TINYINT NULL,
  `Commande_idCommande` INT NOT NULL,
  `Entreprot_idEntreprot` INT NOT NULL,
  `Taille_idTaille` INT NOT NULL,
  `Couleur_idCouleur` INT NOT NULL,
  `Materiel_idMateriel` INT NOT NULL,
  PRIMARY KEY (`idProduit`),
  UNIQUE INDEX `idProduit_UNIQUE` (`idProduit` ASC),
  INDEX `fk_Produit_Commande1_idx` (`Commande_idCommande` ASC),
  INDEX `fk_Produit_Entreprot1_idx` (`Entreprot_idEntreprot` ASC),
  INDEX `fk_Produit_Taille1_idx` (`Taille_idTaille` ASC),
  INDEX `fk_Produit_Couleur1_idx` (`Couleur_idCouleur` ASC),
  INDEX `fk_Produit_Materiel1_idx` (`Materiel_idMateriel` ASC),
  CONSTRAINT `fk_Produit_Commande1`
    FOREIGN KEY (`Commande_idCommande`)
    REFERENCES `Chaussure`.`Commande` (`idCommande`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Produit_Entreprot1`
    FOREIGN KEY (`Entreprot_idEntreprot`)
    REFERENCES `Chaussure`.`Entreprot` (`idEntreprot`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Produit_Taille1`
    FOREIGN KEY (`Taille_idTaille`)
    REFERENCES `Chaussure`.`Taille` (`idTaille`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Produit_Couleur1`
    FOREIGN KEY (`Couleur_idCouleur`)
    REFERENCES `Chaussure`.`Couleur` (`idCouleur`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Produit_Materiel1`
    FOREIGN KEY (`Materiel_idMateriel`)
    REFERENCES `Chaussure`.`Materiel` (`idMateriel`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Chaussure`.`User_has_Banque`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Chaussure`.`User_has_Banque` ;

CREATE TABLE IF NOT EXISTS `Chaussure`.`User_has_Banque` (
  `User_idUser` INT NOT NULL,
  `Banque_idBanque` INT NOT NULL,
  PRIMARY KEY (`User_idUser`, `Banque_idBanque`),
  INDEX `fk_User_has_Banque_Banque1_idx` (`Banque_idBanque` ASC),
  INDEX `fk_User_has_Banque_User1_idx` (`User_idUser` ASC),
  CONSTRAINT `fk_User_has_Banque_User1`
    FOREIGN KEY (`User_idUser`)
    REFERENCES `Chaussure`.`User` (`idUser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_User_has_Banque_Banque1`
    FOREIGN KEY (`Banque_idBanque`)
    REFERENCES `Chaussure`.`Banque` (`idBanque`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
