-- MySQL Script generated by MySQL Workbench
-- Mon Mar 30 14:38:25 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema products
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `products` ;

-- -----------------------------------------------------
-- Schema products
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `products` DEFAULT CHARACTER SET utf8 ;
USE `products` ;

-- -----------------------------------------------------
-- Table `products`.`Category`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `products`.`Category` ;

CREATE TABLE IF NOT EXISTS `products`.`Category` (
  `idCategory` INT NOT NULL,
  `nameCategory` VARCHAR(45) NOT NULL,
  `dateAddCategory` VARCHAR(45) NOT NULL,
  `dateUpdateCategory` VARCHAR(45) NULL,
  PRIMARY KEY (`idCategory`),
  UNIQUE INDEX `idCategory_UNIQUE` (`idCategory` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `products`.`product`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `products`.`product` ;

CREATE TABLE IF NOT EXISTS `products`.`product` (
  `idproduct` INT NOT NULL AUTO_INCREMENT,
  `nameProduct` VARCHAR(45) NULL,
  `dateAdd` DATETIME NOT NULL,
  `Category_idCategory` INT NOT NULL,
  `priceProduct` DECIMAL(6) NOT NULL,
  `dateAdd` DATETIME NOT NULL,
  `dateUpdate` DATETIME NULL,
  PRIMARY KEY (`idproduct`),
  UNIQUE INDEX `idproduct_UNIQUE` (`idproduct` ASC) VISIBLE,
  INDEX `fk_product_Category1_idx` (`Category_idCategory` ASC) VISIBLE,
  CONSTRAINT `fk_product_Category1`
    FOREIGN KEY (`Category_idCategory`)
    REFERENCES `products`.`Category` (`idCategory`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- -----------------------------------------------------
-- Data for table `products`.`Category`
-- -----------------------------------------------------
START TRANSACTION;
USE `products`;
INSERT INTO `products`.`Category` (`idCategory`, `nameCategory`, `dateAddCategory`, `dateUpdateCategory`) VALUES (1, 'Apple', DEFAULT, NULL);
INSERT INTO `products`.`Category` (`idCategory`, `nameCategory`, `dateAddCategory`, `dateUpdateCategory`) VALUES (2, 'Samsung', DEFAULT, NULL);

COMMIT;


-- -----------------------------------------------------
-- Data for table `products`.`product`
-- -----------------------------------------------------
START TRANSACTION;
USE `products`;
INSERT INTO `products`.`product` (`idproduct`, `nameProduct`, `dateAdd`, `Category_idCategory`, `priceProduct`, `dateAdd`, `dateUpdate`) VALUES (1, 'Iphone 11', '2019', 1, DEFAULT, DEFAULT, NULL);
INSERT INTO `products`.`product` (`idproduct`, `nameProduct`, `dateAdd`, `Category_idCategory`, `priceProduct`, `dateAdd`, `dateUpdate`) VALUES (2, 'Galaxy S 10', '2017', 2, DEFAULT, DEFAULT, NULL);

COMMIT;

